---
- name: Install and start nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt: 
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
